### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by DarkZo0m** [request-plugins-for-free/SpeedBridge#47]
~~Citizens support for show bridge ( breezly pro fast )~~ (WONT HAPPEN FOR NOW)

~~/Spectate to spectate players~~ (COMPLETE)

~~Bungeemode ( /leave go to lobby server and join automaticly on join )~~ (WONT HAPPEN FOR NOW)

~~Smart Queue ( Check Empty arenas from 1 )~~ (ALREADY EXISTS)

~~Gui for change block~~ (COMPLETE)

**Comment by Tofpu** [comment]
Regarding the first suggestion, 

**For Developers**
I haven't messed around with packets or whatever is needed to achieve that, if anybody knows, contact me!

**Comment by Tofpu** [comment]
The spectator feature will be added in the next release, thank you for the suggestion! :)
