### ISSUE TITLE
Suggsetion! placeholders!

### ISSUE THREAD

**Issue by XDRmc** [request-plugins-for-free/SpeedBridge#54]
add placeholders so you can see peoples score and your time!

**Comment by XDRmc** [comment]
For whatever reason i couldn put suggestion label on

**Comment by Tofpu** [comment]
> add placeholders so you can see peoples score and your time!  

Regarding other people's scores, great idea! but regarding self time, you could use %bridge_score% to see your own score (or timer, both works). type `/island expansions` for some more placeholders like these!

> For whatever reason i couldn put suggestion label on 

I don't think you're supposed to do that, I appreciate it though

**Comment by Tofpu** [comment]
What would be the use of getting other people's scores with a placeholder?

**Comment by XDRmc** [comment]
So you can make a leaderboard on the score board. also  %bridge_livetimer% dosn't work.

**Comment by Tofpu** [comment]
> So you can make a leaderboard on the score board. also %bridge_livetimer% dosn't work.

You can already do that with the existing placeholders. %bridge_leaderboard_(num)% - replace (num) with the leaderboard position that you'd like to fetch.
It's also %bridge-live-timer%, with - in between the live and timer.
