### ISSUE TITLE
Console spam

### ISSUE THREAD

**Issue by XDRmc** [request-plugins-for-free/SpeedBridge#62]
I use this plugin and it spams this:[19:37:20 WARN]: Nag author(s): '[Tofpu]' of 'SpeedBridge' about their usage of System.out/err.print. Please use your plugin's logger instead (JavaPlugin#getLogger).
[19:37:20 INFO]: [SpeedBridge] [STDOUT] [leaderboard, 2]
[19:37:20 INFO]: [SpeedBridge] [STDOUT] [leaderboard, 1]
[19:37:20 INFO]: [SpeedBridge] [STDOUT] [leaderboard, 3]
[19:37:20 INFO]: [SpeedBridge] [STDOUT] [leaderboard, 2]
[19:37:20 INFO]: [SpeedBridge] [STDOUT] [leaderboard, 1]

Over and over and over and over again.

I think it is something to do with leaderboards place holder

**Comment by XDRmc** [comment]
Also i think it would be good if you made a random island join command

**Comment by Tofpu** [comment]
I left over a debug message, apologizes for that.

> Also i think it would be good if you made a random island join command

That feature already exists, `/join` command will look for any available island in order

**Comment by Tofpu** [comment]
I have released a new version that doesn't include the debug message, thank you for reporting it! :)
