### ISSUE TITLE
Session top 3, Daily leaderboards, a placeholder for amount of blocks placed (for scoreboard)

### ISSUE THREAD

**Issue by ImF3** [request-plugins-for-free/SpeedBridge#67]
Could you please make this happen asap!

- ~~Session Top 3~~ (ALREADY SUGGESTED)
- Daily Leaderboard
- ~~A placeholder for amount of blocks placed~~ (COMPLETE)

**Comment by Tofpu** [comment]
The third suggestion has been implemented, be on the lookout for the next spigot release! :)

**Comment by Tofpu** [comment]
Your daily leaderboard suggestion has been paused till further notice.

Join our discord for further information.
